---
version: '3.8'
services:
  app:
    build:
      context: .
      target: dev
    env_file: .env.local
    environment:
      - NODE_ENV=development
    ports:
      - 3000:3000
    command: bash -c 'while !</dev/tcp/postgres/5432; do sleep 1; done; blitz db migrate && blitz start'
    depends_on:
      - postgres
    volumes:
      - .:/app

  postgres:
    image: postgres:12.4
    env_file: .env.local
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: unless-stopped

volumes:
  db-data:
